DELETE FROM product
WHERE name IN (
               'Jabłko',
               'Mleko',
               'Chleb',
               'Masło',
               'Jogurt',
               'Ser Żółty',
               'Szynka',
               'Parówki',
               'Czekolada',
               'Cukierki',
               'Chipsy',
               'Cola',
               'Woda Mineralna',
               'Sok Pomarańczowy',
               'Makaron',
               'Ryż',
               'Ketchup',
               'Majonez',
               'Pomidory',
               'Ogórek',
               'Cebula',
               'Ziemniaki',
               'Sałata',
               'Jajka',
               'Filet z Kurczaka',
               'Karkówka',
               'Łosoś',
               'Tuńczyk',
               'Pizza Mrożona',
               'Lody',
               'Zioła',
               'Mąka',
               'Cukier',
               'Herbata',
               'Kawa',
               'Serek Wiejski',
               'Szpinak',
               'Brokuły',
               'Banany',
               'Gruszki',
               'Winogrona',
               'Jabłka Granny Smith',
               'Mandarynki',
               'Arbuz',
               'Ananas',
               'Papryka Czerwona',
               'Kiszonki',
               'Chleb Bezglutenowy',
               'Ciastka Owsiane',
               'Mięso Wołowe'
    );
