CREATE TABLE users (
   id UUID PRIMARY KEY,
   username VARCHAR(50) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(100) NOT NULL UNIQUE,
   phone_number VARCHAR(20) NOT NULL UNIQUE,
   enabled BOOLEAN NOT NULL,
   role VARCHAR(20) NOT NULL
);

CREATE TABLE addresses (
   id UUID PRIMARY KEY,
   street VARCHAR(255) NOT NULL,
   city VARCHAR(100) NOT NULL,
   state VARCHAR(100) NOT NULL,
   zip_code VARCHAR(20) NOT NULL,
   country VARCHAR(100) NOT NULL,
   user_id UUID NOT NULL,
   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

